platformPath=/Applications/WebStorm.app
kotlin.stdlib.default.dependency=false
org.gradle.jvmargs=-Xmx2g
org.gradle.java.home=/Applications/WebStorm.app/Contents/jbr/Contents/Home
org.gradle.configuration-cache=true
org.gradle.java.installations.paths=/Applications/WebStorm.app/Contents/jbr/Contents/Home
org.gradle.java.installations.auto-download=false
